### ISSUE TITLE
Connection Timed Out stops reconnect attempts

### ISSUE THREAD

**Issue by MarauderKnight3** [AMereBagatelle/AFKPeace#15]
I've set my number of reconnect attempts to 2147483647 and it didn't try to reconnect after each time the connection times out. Is this intentional?
Using the CurseForge variant. If the new version fixes this, then that's fine, but they are all notably marked 4.6.0 .

**Comment by AMereBagatelle** [comment]
It would seem that the reconnection doesn't pick up on the new timed out message, as you were never reconnected in the first place.

What I'm guessing is happening:
- Disconnected
- AFKPeace pings the server to get a response
- Gets a response and tries to connect
- Times out because it got one ping but no stable connection

I think this can be fixed, by strengthening the reconnection protocol to try again if the initial reconnection attempt fails.  Right now, the mod doesn't check whether the client actually got reconnected, only that it can possibly reach the server.

**Comment by MarauderKnight3** [comment]
It may be possible to begin checking after if the player has the right reconnect message, but I don't know how this works.

**Comment by AMereBagatelle** [comment]
I've implemented some code that should help to ensure the client has a stable connection to the server in this commit: https://github.com/AMereBagatelle/AFKPeace/commit/8626cbfab56f206bdf06000a91fd75cee729adba
This may help solve the issue.

**Comment by MarauderKnight3** [comment]
I saw it, it looks very promising. Will try soon. Thanks for keeping this project up and running. Mod creators sometimes just don't get the appreciation they deserve.

**Comment by AMereBagatelle** [comment]
Closing for now, unless someone can prove there's still an issue here.
